# Generated by Django 2.1.7 on 2019-04-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='password',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='node',
            name='username',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
