# Generated by Django 2.1.7 on 2019-04-03 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='url',
            new_name='node_url',
        ),
    ]
