# Generated by Django 2.1.7 on 2019-03-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_author_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='test',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
