# Generated by Django 2.1.7 on 2019-03-26 06:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20190326_0618'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nodes',
            new_name='Node',
        ),
    ]
