# Generated by Django 2.1.7 on 2019-03-26 18:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190326_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/admin/api/', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='friends',
            name='author1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend1', to='api.Author'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='author2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend2', to='api.Author'),
        ),
    ]
