# Generated by Django 2.1.7 on 2019-03-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190312_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicationDate',
            field=models.DateTimeField(),
        ),
    ]
