# Generated by Django 2.1.7 on 2019-03-14 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190312_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_categories', to='api.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth', to='api.Author'),
        ),
        migrations.AlterField(
            model_name='visibletopost',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visible_post', to='api.Post'),
        ),
    ]
