# Generated by Django 2.1.7 on 2019-03-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190326_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='author1_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='friends',
            name='author2_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
