# Generated by Django 2.1.7 on 2019-03-09 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('userName', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('hostName', models.CharField(max_length=100)),
                ('githubUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('published', models.DateTimeField(verbose_name='date published')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Author')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('regected', models.BooleanField(default=False)),
                ('from_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_request_sent', to='api.Author')),
                ('to_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_request_recieved', to='api.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('author1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend1', to='api.Author')),
                ('author2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend2', to='api.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compressed_img', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicationDate', models.DateTimeField(verbose_name='date published')),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=50)),
                ('permission', models.CharField(choices=[('M', 'me'), ('L', 'permitted authors'), ('F', 'my friends'), ('FF', 'friends of friends'), ('FH', 'friends on my host'), ('P', 'public')], default='P', max_length=2)),
                ('permitted_authors', models.TextField(null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Author')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='post_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Post'),
        ),
    ]
