# Generated by Django 2.1.7 on 2019-03-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190310_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publicationDate',
            field=models.DateField(),
        ),
    ]
