# Generated by Django 2.1.7 on 2019-03-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190309_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='post_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='postid',
        ),
        migrations.AddField(
            model_name='comment',
            name='contentType',
            field=models.CharField(choices=[('text/markdown', 'text/markdown'), ('text/plain', 'text/plain'), ('application/base64', 'application/base64'), ('image/png;base64', 'image/png;base64'), ('image/jpeg;base64', 'image/jpeg;base64')], default='text/plain', max_length=32),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
