# Generated by Django 2.1.7 on 2019-03-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190310_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publicationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
